"""empty message

Revision ID: 104672dd235b
Revises: d204b83df07e
Create Date: 2019-07-31 21:15:44.148483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104672dd235b'
down_revision = 'd204b83df07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
